<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<div class="alert alert-block">
  				<h3>帐号被禁用</h3>
  				<p>您的帐号已经被管理员禁用，如有疑问，请联系 contact@shashi-inc.com</p>
  				<p>祝您小黑屋之旅愉快</p>
			</div>

			<a href="/" class="btn btn-success btn-lg">返回首页</a>
		</div>
		<div class="col-md-5">
			<img src="/css/sc/404.jpg">
		</div>
	</div>
</div>
