<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<div class="alert alert-error">
  				<h3>来晚了</h3>
  				<p>该网址被创建者设置了最多访问N次,您是那N+1位</p>
			</div>
			<div class="alert alert-info">
				<h4>提示</h4>
				<p>注册会员之后可以享受高级功能</p>
			</div>
			<a href="/user/register" class="btn btn-info btn-lg">马上注册</a>
			<a href="/" class="btn btn-success btn-lg">返回首页</a>
		</div>
		<div class="col-md-5">
			<img src="/css/sc/404.jpg">
		</div>
	</div>
</div>
