<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-md-5 col-md-offset-2">
			<h1>这个页面真没有</h1>
			<br>
			<hr>
			<br>
			<a  href="javascript:history.go(-1);" class="btn btn-lg btn-success">返回上一页</a> &nbsp;&nbsp;<a href="/" class="btn btn-lg btn-primary">返回首页</a>
		</div>
		<div class="col-md-5">
			<img src="/css/sc/404.jpg">
		</div>
	</div>
</div>
