<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<div class="alert alert-block">
  				<h3>帐号需要激活</h3>
  				<p>帐号还没激活</p>
  				<p>由于最近恶意用户的数量激增，对我站造成了很大的困扰，故实行帐号激活机制，给你带来的不便敬请谅解</p>
			</div>

			<a href="/account/active" class="btn btn-success btn-lg">立即激活帐号</a>
		</div>
		<div class="col-md-5">
			<img src="/css/sc/404.jpg">
		</div>
	</div>
</div>
<script type="text/javascript">
window.location.href="http://cmcc.in/account/active";
</script>