
 <script type="text/javascript">
function closeWin() {

    window.opener=null;

    window.open('','_self');

    window.close();

}
$(document).ready(function(){
	setTimeout(closeWin,1000);
});
</script>
<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-md-9 col-md-offset-2">
			<div class="alert alert-success">
  				<h3>充值成功</h3>
  				<p>您的订单充值成功,1秒后本页面自动关闭</p>
			</div>

			<a href="javascript:void(0);" class="btn btn-success btn-lg" onclick="javascrpt:closeWin();">关闭本页</a>
		</div>
	</div>
</div>
