<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<div class="alert alert-block">
  				<h3>需要密码</h3>
  				<p>本短网址需要输入一个正确的密码才能访问</p>
			</div>
			<br>
			<form class="form-inline" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
  				<input type="password" class="input-small col-md-3" name='password' placeholder="请输入密码">
  				<button type="submit" class="btn btn-primary">提交</button>
			</form>
			<br>
			<hr>
			<br>
			<a href="/user/register" class="btn btn-info btn-lg">注册</a>
			<a href="/" class="btn btn-success btn-lg">返回首页</a>
		</div>
		<div class="col-md-5">
			<img src="/css/sc/404.jpg">
		</div>
	</div>
</div>
