<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<div class="alert alert-block">
  				<h3>等待审核</h3>
  				<p>该短网址是由游客添加的，需要管理员审核之后才能正常跳转</p>
			</div>
			<div class="alert alert-info">
				<h4>提示</h4>
				<p>注册会员之后添加的网址不用等待审核就能直接跳转哦！</p>
			</div>
			<a href="/user/register" class="btn btn-info btn-lg">马上注册</a>
			<a href="/" class="btn btn-success btn-lg">返回首页</a>
		</div>
		<div class="col-md-5">
			<img src="/css/sc/404.jpg">
		</div>
	</div>
</div>
