<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<div class="alert alert-error">
  				<h3>密码错误</h3>
  				<p>你输入的密码不对</p>
			</div>
			<br>
			<a href="<?php echo $_SERVER['REQUEST_URI']; ?>" class="btn btn-danger btn-lg">返回重新输入密码</a>
			<br>
			<hr>
			<br>
			<a href="/user/register" class="btn btn-info btn-lg">注册</a>
			<a href="/" class="btn btn-success btn-lg">返回首页</a>
		</div>
		<div class="col-md-5">
			<img src="/css/sc/404.jpg">
		</div>
	</div>
</div>
