<!DOCTYPE html>
<html>
  <head>
    <title>登陆 - 沙时通行证</title>
    <!--link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700" media="all" rel="stylesheet" type="text/css" /-->
    <link href="/ios7/stylesheets/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/font-awesome.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/se7en-font.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/style.css" media="all" rel="stylesheet" type="text/css" />
    <script src="/ios7/jq.js" type="text/javascript"></script>
    <script src="/ios7/ui/jquery-ui.js" type="text/javascript"></script>
    <script src="/ios7/javascripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="/ios7/javascripts/modernizr.custom.js" type="text/javascript"></script><!--此js的作用是使选择框变好看-->
    <!--[if lt IE 9]>
      <script src="javascripts/excanvas.min.js" type="text/javascript"></script>
      <script src="javascripts/respond.js" type="text/javascript"></script>
    <![endif]--> 
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
  </head>
  <script type="text/javascript">
    function checkislogin(){
                    $.get("http://passport.shashi-inc.com/user/islogin",function(d){
                            if (d.status==1) {
                                    window.location.href="http://passport.shashi-inc.com/user/adminjump";
                                    // alert("你已经登陆了");
                            }else{
                                    setTimeout(checkislogin,2500);
                            }
                    },"json");
          
    }
    $(document).ready(function(){
          $(".login-container").addClass("active");//显示主题窗口
          checkislogin();
    });

  </script>
  <script>
  
  $(window).load(function() {
      
    });
  $(document).ready(function(){
  });

  </script>
  <body class="login1">
    <!-- Login Screen -->
    <div class="login-wrapper">
      <div class="login-container">
        <h1 style="font-size:20px;margin-top:18px;">扫描二维码以登陆</h1>
        <img src="<?php echo $url; ?>">

        
      </div>
    </div>
    <!-- End Login Screen -->
  </body>
</html>