<?php 
require_once(PUB_TPL."/public/header.phtml");
require_once(PUB_TPL."/public/topmenu.phtml");
?>
<style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
 

<div class="container" style="margin-top:60px">

      <form class="form-signin" method="post" action="/user/login">
        <h2 class="form-signin-heading">请登陆</h2>
        <input type="text" name="username" class="input-block-level" placeholder="用户名">
        <input type="password" name="password" class="input-block-level" placeholder="密码">
        <input type="password" name="password2" class="input-block-level" placeholder="旧版动态口令" value="">
        <input type="password" name="password3" class="input-block-level" placeholder="新版动态口令" value="">
        <label>注：<small>新旧动态口令只需选填一个</small></label>
        <label class="checkbox">
          <input type="checkbox" value="1" name="remember" disabled="disabled"> 记住
        </label>
        <input class="btn btn-large btn-primary" type="submit" name="submit" value="登陆">
      </form>

    </div> <!-- /container -->










 
<?php
require_once(PUB_TPL."/public/footer.phtml");
?>
