<!DOCTYPE html>
<html>
  <head>
    <title>注册 - 沙时通行证</title>
    <link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/font-awesome.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/se7en-font.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/style.css" media="all" rel="stylesheet" type="text/css" />
    <script src="/ios7/jq.js" type="text/javascript"></script>
    <script src="/ios7/ui/jquery-ui.js" type="text/javascript"></script>
    <script src="/ios7/javascripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="/ios7/md5.js" type="text/javascript"></script>
    <!--[if lt IE 9]>
    <script src="/ios7/javascripts/respond.js" type="text/javascript"></script>
    <![endif]--> 
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
    <style type="text/css">
    #yzm {background-color: rgba(0,0,0,0.6);}
    #vimg {cursor: pointer;}
    </style>
  </head>
  <script>
  
  $(window).load(function() {
      return $(".login-container").addClass("active");//显示主题窗口
    });
  $(document).ready(function(){

  });

  </script>
  <body class="login1 signup">
    <!-- Login Screen -->
    <div class="login-wrapper">
      <div class="login-container">
        <h1 style="font-size:60px;margin-top:18px;">登陆</h1>
        <form action="/user/register" onsubmit="return check();">
          <div class="form-group">
            <input class="form-control" id="account" type="text" value="" placeholder="用户名/手机号/邮箱" >
          </div>
          <div class="form-group">
            <input class="form-control" id="pass1" type="password" value="" placeholder="密码">
          </div>
          <div class="form-options clearfix">
            <a class="pull-right" href="#">Forgot password?</a>
            <div class="text-left">
              <label class="checkbox"><input type="checkbox"><span>Remember me</span></label>
            </div>
          </div>
        </form>
        <p class="signup">
          已经有帐号？ <a href="/user/login">马上登录</a>
        </p>
      </div>
    </div>
    <!-- End Login Screen -->
    <div class="modal fade" id="notice">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">提示</h4>
          </div>
          <div class="modal-body">
            <p id="noticecontent"></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">好</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div class="modal fade" id="yzm">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">请输入验证码</h4>
          </div>
          <div class="modal-body">
            <img id="vimg" src="/verify_code.php" style="width:300px;height:100px">
            <br>
            <br>
            <div class="col-lg-6">
              <input type="text" id="verifyvalue" class="form-control" placeholder="验证码内容"">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" id="vokbtn" class="btn btn-primary" disabled="disabled" data-dismiss="modal">确定</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->




  </body>
</html>