<!DOCTYPE html>
<html>
  <head>
    <title>注册 - 沙时通行证</title>
    <link href="/ios7/stylesheets/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/font-awesome.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/se7en-font.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/ios7/stylesheets/style.css" media="all" rel="stylesheet" type="text/css" />
    <script src="/ios7/jq.js" type="text/javascript"></script>
    <script src="/ios7/ui/jquery-ui.js" type="text/javascript"></script>
    <script src="/ios7/javascripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="/ios7/javascripts/modernizr.custom.js" type="text/javascript"></script><!--此js的作用是使选择框变好看-->
    <script src="/ios7/md5.js" type="text/javascript"></script>
    <!--[if lt IE 9]>
    <script src="/ios7/javascripts/respond.js" type="text/javascript"></script>
    <![endif]--> 
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
    <style type="text/css">
    #yzm {background-color: rgba(0,0,0,0.6);}
    #vimg {cursor: pointer;}
    </style>
  </head>
  <script>
  
  verifycode = <?php echo $verify; ?>;//0=不需要验证码,1=需要
  seed = '';//答案的种子
  secret = '';//答案的密文
  localverify = false;//本地验证验证码正确性的开关
  function check(){//检查表单的完整和合法性
    var regname = $("#account").val();
    var pass = $("#pass1").val();
    var pass2 = $("#pass2").val();
    var verify=$("#verifyvalue").val();
    if (regname==''||regname==null) {
      $("#noticecontent").html("注册用户名不能为空");
      $("#notice").modal("toggle");
      return false;
    }
    if (pass==''||pass==null) {
      $("#noticecontent").html("密码不能为空");
      $("#notice").modal("toggle");
      return false;
    } 
    if (pass!=pass2) {
      $("#noticecontent").html("两次输入的密码不一致");
      $("#notice").modal("toggle");
      return false;
    }
    if (verifycode==1&&(verify==''||verify==null)) {
      $("#noticecontent").html("验证码还没填，请刷新页面重填");
      $("#notice").modal("toggle");
      return false;
    }
    //submit
    $.post("/user/register",{"submit":"yes","name":regname,"password":pass,"verifycode":verify},function(d){
      if (d.status==1) {
        $("#noticecontent").html(d.data);
        $("#notice").modal("toggle");
      }else{
        $("#noticecontent").html(d.data);
        $("#notice").modal("toggle");
      }
    },"json");
    return false;
  }
  function checkv(){//检查验证码正确性
    var v=$("#verifyvalue").val();
    if (localverify==false) {
        if (v.length==4) {
          $("#vokbtn").removeAttr("disabled");
        }else{
          $("#vokbtn").attr("disabled","disabled");
        }
    }else{
      var localsecret = md5(v+seed);
      if (localsecret==secret) {
        $("#vokbtn").removeAttr("disabled");
        $("#vokbtn").attr("class","btn btn-success")
      }else{
        $("#vokbtn").attr("disabled","disabled");
      }
    }

  }
  function checkifshowv(){//检查要不要显示验证码
    if (verifycode==1) {
      $('#yzm').modal({
        keyboard: false,
        backdrop: false,
        show: true
      });
      setanswer();
      $("#verifyvalue").focus();
      setInterval(checkv,1000);
    }
  }
  function setanswer(){//获取并设置验证码答案
    $.get("/code_seed.php?hash="+Math.random(),function(d){
      if (d.status == 1) {
        localverify=true;
        seed=d.seed;
        secret=d.secret;
      }else{
        localverify=false;
      }
    },"json");
  }
  $(window).load(function() {
      return $(".login-container").addClass("active");//显示主题窗口
    });
  $(document).ready(function(){
    $("#vimg").click(function(){//刷新验证码
      $(this).attr("src","/verify_code.php?hash="+Math.random());
      setTimeout(setanswer,1000);
    });


  });

  </script>
  <body class="login1 signup">
    <!-- Login Screen -->
    <div class="login-wrapper">
      <div class="login-container">
        <h1 style="font-size:60px;margin-top:18px;">注册</h1>
        <form action="/user/register" onsubmit="return check();">
          <div class="form-group">
            <input class="form-control" id="account" type="text" value="" placeholder="用户名/手机号/邮箱" onblur="checkifshowv()">
          </div>
          <div class="form-group">
            <input class="form-control" id="pass1" type="password" value="" placeholder="密码">
          </div>
          <div class="form-group">
            <input class="form-control" id="pass2" type="password" value="" placeholder="重复密码"><input type="submit" value="&#xf054;">
          </div>
          <div class="form-options">
            <label class="checkbox"><input type="checkbox" checked="checked" disabled="disabled"><span>同意<a href="/" target="_blank">《用户协议和条款》</a></span></label>
          </div>
        </form>
        <p class="signup">
          已经有帐号？ <a href="/user/login">马上登录</a>
        </p>
      </div>
    </div>
    <!-- End Login Screen -->
    <div class="modal fade" id="notice">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">提示</h4>
          </div>
          <div class="modal-body">
            <p id="noticecontent"></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">好</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div class="modal fade" id="yzm">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">请输入验证码</h4>
          </div>
          <div class="modal-body">
            <img id="vimg" src="/verify_code.php" style="width:300px;height:100px">
            <br>
            <br>
            <div class="col-lg-6">
              <input type="text" id="verifyvalue" class="form-control" placeholder="验证码内容"">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" id="vokbtn" class="btn btn-primary" disabled="disabled" data-dismiss="modal">确定</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->




  </body>
</html>