<?php 
require_once(PUB_TPL."/public/header.phtml");
require_once(PUB_TPL."/public/topmenu.phtml");
$activetab="indexpage";
?>
<script type="text/javascript">
// ajaxlock = 0;
function checkislogin(){
        // if (ajaxlock==0){
                // ajaxlock=1;
                $.get("http://hm.cmcc.in/user/islogin",function(d){
                        if (d.status==1) {
                                window.location.href="http://hm.cmcc.in/project/index";
                        }else{
                                // ajaxlock=0;
                                setTimeout(checkislogin,2500);
                        }
                },"json");
        // }
}
$(document).ready(function(){
        // setInterval(checkislogin,1000);
        checkislogin();
});

</script>
<div class="container">
	<div class="jumbotron">
		<h1 style="text-align: center;">请先登陆</h1>
	</div>
</div>
<div class="container">
                	<div class="row">
                		<div class="col-md-6 col-md-offset-3">
                			<center><h3>新版动态密码器可以扫描以下二维码登陆</h3></center>
                			<center><img src="<?php echo $url;?>"></center>
                		</div>
                	</div>
                </div>                
<?php
require_once(PUB_TPL."/public/footer.phtml");
?>
